apiVersion: 1
datasources:
  - name: PostgreSQL
    uid: PostgreSQL
    type: postgres
    url: aidra-db:5432
    database: aidra
    user: aidra
    secureJsonData:
      password: ${DB_PASSWORD}
    jsonData:
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false

  - name: Prometheus
    uid: Prometheus
    type: prometheus
    url: http://aidra-prom:9090
    isDefault: true
    jsonData:
      timeInterval: 15s

  - name: Loki
    uid: Loki
    type: loki
    url: http://aidra-loki:3100
