"""
Prometheus metrics definitions for AIDRA.

All metrics follow the naming convention `aidra_<subsystem>_<metric>_<unit>`.
Labels are used for dimensionality (profile, model_variant, status, etc.).

Cardinality policy (I-TRACE-3)
------------------------------
The execution UUID (``run_id``) is intentionally **not** a label. Storing
millions of unique label-value combinations would explode Prometheus
TSDB cardinality. Instead the run_id is attached as an **OpenMetrics
exemplar** to ``aidra_pipeline_runs_total`` and
``aidra_inference_duration_seconds``. Exemplars are exposed only when
clients request the OpenMetrics content-type
(``application/openmetrics-text``); plain Prometheus scrape stays
cardinality-free.

This closes invariant I-TRACE-3 (run_id end-to-end across logs +
metrics) without sacrificing scrape stability.

Usage:
    from src.observability.prometheus_metrics import (
        PIPELINE_RUNS_TOTAL, DETECTIONS_TOTAL, INFERENCE_DURATION,
        generate_metrics_response,
    )

    PIPELINE_RUNS_TOTAL.labels(
        profile="ground", model_variant="yolov8n", status="success"
    ).inc(exemplar={"trace_id": str(execution_id)})

    with INFERENCE_DURATION.labels(profile="ground", model_variant="yolov8n").time():
        result = run_inference(image)
"""

from __future__ import annotations

from prometheus_client import (
    CONTENT_TYPE_LATEST,
    REGISTRY,
    Counter,
    Gauge,
    Histogram,
    Info,
    generate_latest,
)
from prometheus_client.openmetrics.exposition import (
    CONTENT_TYPE_LATEST as OPENMETRICS_CONTENT_TYPE,
)
from prometheus_client.openmetrics.exposition import (
    generate_latest as openmetrics_generate_latest,
)

# ---------------------------------------------------------------------------
# Counters
# ---------------------------------------------------------------------------

PIPELINE_RUNS_TOTAL = Counter(
    "aidra_pipeline_runs_total",
    "Total pipeline executions",
    ["profile", "model_variant", "status"],  # status: success, error, timeout, oom
)

DETECTIONS_TOTAL = Counter(
    "aidra_detections_total",
    "Total detections across all runs",
    ["source", "profile"],  # source: cfar, yolo, fused
)

SCENES_PROCESSED_TOTAL = Counter(
    "aidra_scenes_processed_total",
    "Total scenes evaluated by preprocess_full, by quality flag (I-SAR-1).",
    ["quality"],  # quality: valid, invalid
)

IMAGES_DOWNLOADED_TOTAL = Counter(
    "aidra_images_downloaded_total",
    "Total satellite images downloaded",
)

TIPS_GENERATED_TOTAL = Counter(
    "aidra_tips_generated_total",
    "Total tips generated by Tip & Cue evaluator",
)

CUES_EXECUTED_TOTAL = Counter(
    "aidra_cues_executed_total",
    "Total cues executed",
    ["status"],  # confirmed, discarded
)

DECISION_ACTION = Counter(
    "aidra_decision_action_total",
    "Autonomous decisions made",
    ["action"],  # "process", "fallback_cfar", "skip"
)

DRIFT_ALERTS = Counter(
    "aidra_drift_alerts_total",
    "Drift detection alerts",
    ["metric"],  # "num_detections", "avg_confidence", "spatial"
)

# ---------------------------------------------------------------------------
# Histograms
# ---------------------------------------------------------------------------

INFERENCE_DURATION = Histogram(
    "aidra_inference_duration_seconds",
    "Inference time per pipeline run",
    ["profile", "model_variant"],
    buckets=[0.05, 0.1, 0.25, 0.5, 1.0, 2.5, 5.0, 10.0, 30.0, 60.0],
)

DOWNLOAD_DURATION = Histogram(
    "aidra_download_duration_seconds",
    "Satellite image download time",
    buckets=[10, 30, 60, 120, 300, 600],
)

# ---------------------------------------------------------------------------
# Gauges
# ---------------------------------------------------------------------------

PEAK_RAM_MB = Gauge(
    "aidra_peak_ram_mb",
    "Peak RAM usage during last inference",
    ["profile", "model_variant"],
)

CPU_USAGE_PERCENT = Gauge(
    "aidra_cpu_usage_percent",
    "Average CPU usage during last inference",
    ["profile", "model_variant"],
)

MODEL_SIZE_MB = Gauge(
    "aidra_model_size_mb",
    "Model file size in MB",
    ["model_variant"],
)

ACTIVE_CUES = Gauge(
    "aidra_active_cues",
    "Number of pending cues in tasking queue",
)

# -- Orbital / Energy gauges (Modules 9 & 12) --

ENERGY_JOULES = Gauge(
    "aidra_energy_joules",
    "Estimated energy consumption per inference",
    ["profile", "model_variant", "processor"],
)

TOPS_PER_WATT = Gauge(
    "aidra_tops_per_watt",
    "Tera operations per second per watt",
    ["model_variant", "processor"],
)

IMAGES_PER_ORBIT = Gauge(
    "aidra_images_per_orbit",
    "Max images processable per orbit with current model/profile",
    ["model_variant", "profile", "satellite_type"],
)

BITFLIP_DEGRADATION = Gauge(
    "aidra_bitflip_degradation_pct",
    "Detection degradation under simulated bit-flips",
    ["num_flips", "model_variant"],
)

BATTERY_LEVEL_WH = Gauge(
    "aidra_sim_battery_wh",
    "Simulated battery level during orbit simulation",
)

# ---------------------------------------------------------------------------
# Info
# ---------------------------------------------------------------------------

SYSTEM_INFO = Info(
    "aidra_system",
    "System information",
)

# ---------------------------------------------------------------------------
# Metrics endpoint helper
# ---------------------------------------------------------------------------


def generate_metrics_response(
    accept_header: str | None = None,
) -> tuple[bytes, str]:
    """Generate the Prometheus metrics exposition payload.

    When the caller advertises support for OpenMetrics via the
    ``Accept`` header (e.g. ``application/openmetrics-text``), the
    response uses the OpenMetrics 1.0.0 format so that exemplars
    (the ``run_id`` / ``trace_id`` link) are visible. Otherwise the
    classic Prometheus text format is used (no exemplars).

    Returns:
        A tuple of ``(body_bytes, content_type)`` suitable for returning from
        an HTTP handler.  Example usage in FastAPI::

            @app.get("/api/metrics")
            async def metrics_endpoint(request: Request):
                accept = request.headers.get("accept")
                body, content_type = generate_metrics_response(accept)
                return Response(content=body, media_type=content_type)
    """
    if accept_header and "application/openmetrics-text" in accept_header:
        body: bytes = openmetrics_generate_latest(REGISTRY)
        return body, OPENMETRICS_CONTENT_TYPE
    body = generate_latest(REGISTRY)
    return body, CONTENT_TYPE_LATEST
