"""
Traceability endpoint.

Returns the complete provenance chain for a pipeline execution:
all execution_log fields, associated detections, upstream trigger
(if the execution was a cue), and downstream cues generated.
"""

from __future__ import annotations

import logging
from uuid import UUID

from fastapi import APIRouter, HTTPException

from src.db.connection import db
from src.db.queries import SELECT_EXECUTION_BY_ID

logger = logging.getLogger("aidra.api.traceability")

router = APIRouter(tags=["traceability"])

# ---------------------------------------------------------------------------
# SQL for associated data
# ---------------------------------------------------------------------------

_SELECT_DETECTIONS_FOR_EXECUTION = """
    SELECT
        d.*,
        ST_X(d.center_geo) AS longitude,
        ST_Y(d.center_geo) AS latitude,
        ST_AsGeoJSON(d.center_geo) AS center_geojson,
        ST_AsGeoJSON(d.bbox_geo) AS bbox_geojson
    FROM detections d
    WHERE d.execution_id = $1
    ORDER BY d.confidence DESC
"""

_SELECT_UPSTREAM_CUE = """
    SELECT *, ST_AsGeoJSON(target_bbox) AS target_bbox_geojson
    FROM tasking_queue
    WHERE execution_id = $1
    LIMIT 1
"""

_SELECT_DOWNSTREAM_CUES = """
    SELECT *, ST_AsGeoJSON(target_bbox) AS target_bbox_geojson
    FROM tasking_queue
    WHERE triggered_by = $1
    ORDER BY created_at
"""


def _safe_dict(row) -> dict:  # type: ignore[no-untyped-def]
    """Convert an asyncpg Record to a dict, dropping non-serializable
    geometry columns."""
    d = dict(row)
    # Remove raw PostGIS geometry binary columns
    for key in list(d.keys()):
        val = d[key]
        if isinstance(val, (bytes, memoryview)):
            d.pop(key, None)
    return d


@router.get("/traceability/{execution_id}")
async def get_traceability(execution_id: UUID) -> dict:
    """Return the full provenance chain for a pipeline execution.

    The response includes:

    - **execution**: all columns from ``execution_log`` (image hash,
      model hash, output hash, timing metrics, constraint profile, etc.).
    - **detections**: list of individual vessel detections produced by
      this execution.
    - **upstream_cue**: if this execution was triggered by a Tip & Cue
      entry, the corresponding ``tasking_queue`` record.
    - **downstream_cues**: any cues that were generated as a result of
      detections from this execution.

    Raises:
        HTTPException 404: if the execution ID does not exist.
    """
    # Fetch the execution record
    try:
        exec_row = await db.fetchrow(SELECT_EXECUTION_BY_ID, execution_id)
    except Exception as exc:
        logger.error(
            "Failed to fetch execution %s: %s", execution_id, exc, exc_info=True
        )
        raise HTTPException(
            status_code=500,
            detail=f"Database error: {exc}",
        ) from exc

    if exec_row is None:
        raise HTTPException(
            status_code=404,
            detail=f"Execution {execution_id} not found",
        )

    execution = _safe_dict(exec_row)

    # Fetch associated detections
    try:
        det_rows = await db.fetch(
            _SELECT_DETECTIONS_FOR_EXECUTION, execution_id
        )
        detections = [_safe_dict(r) for r in det_rows]
    except Exception as exc:
        logger.warning(
            "Could not fetch detections for execution %s: %s",
            execution_id,
            exc,
        )
        detections = []

    # Fetch upstream cue (if this execution was a cue)
    upstream_cue = None
    try:
        cue_row = await db.fetchrow(_SELECT_UPSTREAM_CUE, execution_id)
        if cue_row:
            upstream_cue = _safe_dict(cue_row)
    except Exception as exc:
        logger.debug("Could not fetch upstream cue: %s", exc)

    # Fetch downstream cues generated by this execution
    downstream_cues: list[dict] = []
    try:
        cue_rows = await db.fetch(_SELECT_DOWNSTREAM_CUES, execution_id)
        downstream_cues = [_safe_dict(r) for r in cue_rows]
    except Exception as exc:
        logger.debug("Could not fetch downstream cues: %s", exc)

    return {
        "execution": execution,
        "detections": detections,
        "upstream_cue": upstream_cue,
        "downstream_cues": downstream_cues,
    }
